{
 "title": "Loki / Promtail",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(loki_build_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(promtail_build_info{cluster=~\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Targets & Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promtail_targets_active_total{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Active Targets"
    }
   ]
  },
  {
   "title": "Active Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promtail_files_active_total{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Active Targets"
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_read_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "logs read"
    }
   ]
  },
  {
   "title": "Lines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_read_lines_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "lines read"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(promtail_request_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99, avg by (pod) (rate(promtail_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"promtail-metrics\"}[$__rate_interval])))",
     "legendFormat": "p99 {{pod}}"
    },
    {
     "expr": "quantile(0.50, avg by (pod) (rate(promtail_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"promtail-metrics\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (job) (rate(promtail_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"promtail-metrics\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}