{
 "title": "Promtail 429s/413s",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "429 - Too Many Reqs",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({app=\"promtail\"} |= `Too Many Requests`[1m])",
     "legendFormat": "Node : {{node_name}} <---> Pod : {{pod}}"
    }
   ]
  },
  {
   "title": "413 - Request Entity Too Large",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count_over_time({app=\"promtail\"} |= `Request Entity Too Large`[1m])",
     "legendFormat": "Node : {{node_name}} <---> Pod : {{pod}}"
    }
   ]
  },
  {
   "title": "Logs - 429",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{app=\"promtail\"} |= `error` |= `429`"
    }
   ]
  },
  {
   "title": "Logs - 413",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{app=\"promtail\"} |= `Request Entity Too Large`"
    }
   ]
  }
 ]
}